name: CI/CD Pi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Bạn có thể thay đổi phiên bản PHP tùy theo yêu cầu

      - name: Install PHP CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Run PHP CodeSniffer
        run: ~/.composer/vendor/bin/phpcs --standard=WordPress .

      - name: Install PHPStan
        run: composer global require phpstan/phpstan

      - name: Run PHPStan
        run: ~/.composer/vendor/bin/phpstan analyse --level=max .
