name: CI/CD PHP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Bạn có thể thay đổi phiên bản PHP tùy theo yêu cầu

      - name: Install Composer
        run: sudo apt-get install -y composer

      - name: Allow Composer Plugin
        run: composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install PHP CodeSniffer and WordPress Coding Standards
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          composer global require "wp-coding-standards/wpcs"
          composer global require "dealerdirect/phpcodesniffer-composer-installer"
          ~/.composer/vendor/bin/phpcs --config-set installed_paths $(composer global config home)/vendor/wp-coding-standards/wpcs
          ~/.composer/vendor/bin/phpcs -i

      - name: Run PHP CodeSniffer
        run: ~/.composer/vendor/bin/phpcs --standard=WordPress .
