name: Deploy WordPress

on:
  push:
    branches:
      - main  # Chạy khi có push lên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Composer dependencies
      run: composer install

    - name: Replace database configuration in wp-config.php
      run: |
        sed -i "s/database_name_here/wordpress_db/g" wp-config.php
        sed -i "s/username_here/root/g" wp-config.php
        sed -i "s/password_here//g" wp-config.php
        sed -i "s/localhost/localhost/g" wp-config.php
      

    - name: Reload Nginx
      run: |
        sudo systemctl reload nginx  # Khởi động lại Nginx để áp dụng thay đổi
