name: PHP Syntax Check

on: [push, pull_request]

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Run PHP Lint on changed PHP files
      run: |
        for file in $(git status -s | grep "^.*\.php$" | awk '{print $2}'); do
          php -l $file
          if [ $? -ne 0 ]; then
            echo "::error file=$file::Failed linting"
            exit 1
          fi
        done
