name: PHP Syntax Check

on: [push, pull_request]

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Get list of changed files
      id: changed-files
      run: |
        git fetch origin main:refs/remotes/origin/main
        git diff --name-only origin/main ${{ github.sha }} > all_changed_files.txt
        echo "All changed files:"
        cat all_changed_files.txt

    - name: Filter PHP files
      run: |
        grep '\.php$' all_changed_files.txt > changed_files.txt || echo "No PHP files changed or an error occurred."
        echo "Filtered PHP files:"
        cat changed_files.txt

    - name: Run PHP Lint
      run: |
        if [ -s changed_files.txt ]; then
          while IFS= read -r file; do
            echo "Checking syntax for $file"
            php -l "$file"
          done < changed_files.txt
        else
          echo "No PHP files changed."
        fi
