name: PHP Lint

on:
  push:
    paths:
      - '**/*.php'
  pull_request:
    paths:
      - '**/*.php'

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer
        run: sudo apt-get install -y composer

      - name: Allow Composer Plugin
        run: composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install dependencies
        run: composer install

      - name: Get list of changed files
        id: changed-files
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} > changed_files.txt

      - name: Run PHP CodeSniffer
        run: |
          if [ -s changed_files.txt ]; then
            vendor/bin/phpcs --standard=WordPress $(cat changed_files.txt | tr '\n' ' ')
          else
            echo "No PHP files changed."
          fi
