name: PHPCS WordPress Coding Standards

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Composer
      run: sudo apt-get install -y composer

    - name: Install PHPCS and WPCS
      run: |
        composer global require "squizlabs/php_codesniffer=*"
        git clone -b develop https://github.com/WordPress/WordPress-Coding-Standards.git $HOME/wpcs
        git clone https://github.com/PHPCSStandards/PHPCSUtils.git $HOME/PHPCSUtils
        $HOME/.composer/vendor/bin/phpcs --config-set installed_paths $HOME/wpcs,$HOME/PHPCSUtils
        $HOME/.composer/vendor/bin/phpcs --config-set default_standard WordPress

    - name: Run PHPCS
      run: |
        $HOME/.composer/vendor/bin/phpcs helloworld.php
