name: PHP Syntax Check

on: [push, pull_request]

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Run PHP Lint on specific directories
      run: |
        # Kiểm tra các tệp PHP trong các thư mục themes, plugins và tệp cấu hình chính
        for file in $(find wp-content/themes wp-content/plugins . -maxdepth 1 -name "*.php"); do
          echo "Checking syntax of $file"
          php -l $file
          if [ $? -ne 0 ]; then
            echo "Syntax error in $file"
            exit 1
          fi
        done
