name: PHP Syntax Check

on: [push, pull_request]

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Get list of changed PHP files
      id: changed-files
      run: |
        # Determine the base commit
        if [ "${{ github.event.pull_request.base.sha }}" != "" ]; then
          BASE_COMMIT="${{ github.event.pull_request.base.sha }}"
        else
          BASE_COMMIT="origin/main"
        fi

        # Get the list of changed PHP files
        CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRT $BASE_COMMIT ${{ github.sha }} | grep '\.php$')
        
        # Output the list of changed files
        echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV

    - name: Run PHP Lint on changed PHP files
      run: |
        # Check if there are any PHP files to lint
        if [ -z "$changed_files" ]; then
          echo "No PHP files changed."
          exit 0
        fi
        
        # Run lint on each changed PHP file
        for file in $changed_files; do
          php -l $file
          if [ $? -ne 0 ]; then
            echo "::error file=$file::Failed linting"
            exit 1
          fi
        done
      env:
        changed_files: ${{ env.changed_files }}
