name: PHP Syntax Check

on: [push, pull_request]

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Get list of changed PHP files
      id: changed-files
      run: |
        # Get the list of changed PHP files in the current commit
        CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '\.php$')
        
        # Output the list of changed files
        echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV

    - name: Run PHP Lint on changed PHP files
      run: |
        # Check if there are any PHP files to lint
        if [ -z "$changed_files" ]; then
          echo "No PHP files changed."
          exit 0
        fi
        
        # Run lint on each changed PHP file
        for file in $changed_files; do
          php -l $file
          if [ $? -ne 0 ]; then
            echo "::error file=$file::Failed linting"
            exit 1
          fi
        done
      env:
        changed_files: ${{ env.changed_files }}
