name: PHP Lint

on:
  push:
    paths:
      - '**/*.php'
  pull_request:
    paths:
      - '**/*.php'

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Bạn có thể thay đổi phiên bản PHP tùy theo yêu cầu

      - name: Install Composer
        run: sudo apt-get install -y composer

      - name: Install dependencies
        run: composer install

      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs --standard=WordPress .
