name: PHP Syntax Check

on: [push, pull_request]

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Run PHP Lint on changed PHP files
      run: |
        # Get the list of changed PHP files
        changed_files=$(git diff --name-only --diff-filter=ACMRT HEAD~1 | grep '\.php$')
        
        # Check if there are any PHP files to lint
        if [ -z "$changed_files" ]; then
          echo "No PHP files changed."
          exit 0
        fi
        
        # Run lint on each changed PHP file
        for file in $changed_files; do
          php -l $file
          if [ $? -ne 0 ]; then
            echo "::error file=$file::Failed linting"
            exit 1
          fi
        done
