name: PHP Syntax Check

on: [push, pull_request]

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Get list of changed PHP files
      id: changed-files
      run: |
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.php$' || true)
        echo "Changed PHP files: $CHANGED_FILES"
        echo "::set-output name=files::$CHANGED_FILES"

    - name: Run PHP Lint
      run: |
        if [ -z "${{ steps.changed-files.outputs.files }}" ]; then
          echo "No PHP files changed."
          exit 0
        fi
        for file in ${{ steps.changed-files.outputs.files }}; do
          echo "Checking syntax of $file"
          php -l $file
          if [ $? -ne 0 ]; then
            echo "Syntax error in $file"
            exit 1
          fi
        done
      if: steps.changed-files.outputs.files != ''
