name: PHPCS CI

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Composer
      run: sudo apt-get install -y composer

    - name: Install PHPCS
      run: |
        composer global require "squizlabs/php_codesniffer=*"

    - name: List files in the repository
      run: ls -R

    - name: Run PHPCS
      run: |
        $HOME/.composer/vendor/bin/phpcs --standard=PSR12 helloworld.php
