name: PHP Syntax Check

on: [push, pull_request]

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Run PHP Lint on all PHP files
      run: |
        find . -name "*.php" -print0 | xargs -0 -n 1 php -l
