name: PHP Syntax Check

on: [push, pull_request]

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Find PHP files changed
      id: files
      run: |
        echo "PHP_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.php$' | xargs)" >> $GITHUB_ENV

    - name: Run PHP Lint on changed PHP files
      run: |
        for file in $PHP_FILES; do
          php -l $file
          if [ $? -ne 0 ]; then
            echo "::error file=$file::Failed linting"
            exit 1
          fi
        done
  
